# Generated by Django 5.1.7 on 2025-03-24 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanbans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added', models.DateTimeField(auto_now=True)),
                ('kanban_field', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='kanbans.kanbanfield')),
            ],
        ),
    ]
