# Generated by Django 5.2 on 2025-04-07 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kanbans", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kanban",
            options={"verbose_name": "Kanban", "verbose_name_plural": "Kanbans"},
        ),
        migrations.AlterModelOptions(
            name="kanbanfield",
            options={"verbose_name": "Field", "verbose_name_plural": "Fields"},
        ),
        migrations.AlterUniqueTogether(
            name="kanbanfield",
            unique_together={("position", "kanban")},
        ),
    ]
